D-PRlME/Togather-iOS

Draw/Draw.xcodeproj/project.pbxproj, Draw/Draw/Assets.xcassets/AppIcon.appiconset/Contents.json, Draw/Draw/Header/Header.swift, Draw/Draw/MoyaClient/PostClient.swift, Draw/Draw/MoyaClient/UserClient.swift
=> 🔀 :: (#1) 클라이언트 & 헤더 세팅

Draw/Draw/View/HomeView.swift
HomeView에 태그의 간격을 조절하였다.
close #3
=> 🔀 :: (#3) HomeView 태그 간격 조절

Draw/Draw/View/HomeView.swift, Draw/Draw/View/SearchView.swift, Draw/Draw/View/TabBarView.swift
SearchView UI 를 만들었다.
close #5
=> 🔀 :: (#5)  SearchView UI

Draw/Draw/View/MyView.swift
=> 🔀 :: (#9) MyView UI

Draw/Draw.xcodeproj/project.pbxproj, Draw/Draw/View/HomeView.swift, Draw/Draw/View/MyView.swift, Draw/Draw/View/SearchView.swift, Draw/Draw/View/TabBarView.swift
=> 🔀 :: (#17) 각 뷰 Stroke 방식 변경(리펙토링)

Draw/Draw/View/EditInfo/DeleteAccount.swift, Draw/Draw/View/EditInfo/EditInfo.swift
=> 🔀 :: (#11) 계정 정보 수정 UI

Draw/Draw/View/HomeView.swift, Draw/Draw/View/SearchView.swift, Draw/Draw/View/WritingView.swift
각 뷰의 stroke 방식 리팩토링하였다.
close #20
=> 🔀 :: (#20) 각 뷰의 stroke 방식 리팩토링

Draw/Draw/ContentView.swift, Draw/Draw/View/myview ->/Developers.swift
=> 🔀 :: (#14) 개발자들 UI

Draw/Draw/View/MyView.swift, Draw/Draw/View/SearchView.swift, Draw/Draw/View/TabBarView.swift
=> 🔀 :: (#26) 노란색 오류 수정

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Togather/Togather.xcodeproj/xcshareddata/xcschemes/Togather.xcscheme
파일 이름을 Draw에서 Togather로 변경할때 일어난 경로 충돌을 수정함
close #40
=> 🔀 :: (#40) 충돌 버그 수정

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/PasswordChangeView/ChangePasswordSuccess.swift, Togather/Togather/View/PasswordChangeView/ChangePasswordVerify.swift, Togather/Togather/View/PasswordChangeView/EnterNewPassword.swift
=> 🔀 :: (#12) 비밀번호 변경 UI

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordSuccess.swift, Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordVerify.swift, Togather/Togather/View/myview ->/PasswordChangeView/EnterNewPassword.swift
=> 🔀 :: (#43) 비밀번호 변경 뷰 리팩토링

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/MoyaClient/PostClient.swift, Togather/Togather/MoyaClient/UserClient.swift
클라이언트 path중 id 부분을 email로 변경하여 리팩토링을 진행함
close #45
=> 🔀 :: (#45) 클라이언트 코드 리팩토링

Togather/Togather/Model/ErrorModel.swift, Togather/Togather/Model/TokenModel.swift
통신에 필요한 TokenModel, ErrorModel를 만들었다
close #46
=> 🔀 :: (#46) 모델 생성

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Model/ErrorModel.swift, Togather/Togather/Model/LookUpMyProfileModel.swift, Togather/Togather/Model/LookUpPostDetailModel.swift, Togather/Togather/Model/LookUpPostModel.swift, Togather/Togather/Model/LookUpTagPostModel.swift, Togather/Togather/Model/LookUpUserProfileModel.swift, Togather/Togather/Model/SearchPostModel.swift, Togather/Togather/Model/TokenModel.swift, Togather/Togather/Model/UploadImageModel.swift
=> 🔀 :: (#49) Model 만들기

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Model/LookUpMyProfileModel.swift
ProfileModel 파일 수정했다.
close #52
=> 🔀 :: (#52) ProfileModel 파일 수정

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/SignInView.swift, Togather/Togather/View/SignUpView/SignUpView.swift, Togather/Togather/ViewModels/EmailDuplicateViewModel.swift, Togather/Togather/ViewModels/LoginViewModel.swift, Togather/Togather/ViewModels/SignUpViewModel.swift
로그인, 회원가입, 이메일 인증 ViewModel 추가후 View에 기능을 넣음
close #51
=> 🔀 :: (#51) ViewModel 추가

Togather/Togather/View/SignInView.swift
SigninView에서 TabBarView로 가는 NavigationLink를 추가하였다.
close #57
=> 🔀 :: (#57) SigninView에 Navigationlink 추가

Togather/Togather/ViewModels/user/EmailDuplicateViewModel.swift
=> 🔀 :: (#61) 메일 중복 확인 VM 파일 추가

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/HomeView.swift, Togather/Togather/View/PostDetail.swift, Togather/Togather/View/SearchView.swift, Togather/Togather/View/ViewSupporter/TagsFlowLayout.swift, Togather/Togather/View/WritingView.swift, Togather/Togather/View/myview ->/MyPost.swift
=> 🔀 :: (#63)FlowLayout Components

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/WritingView.swift
=> 🔀 :: (#69) 글쓰기 기능 추가

Togather/Togather/MoyaClient/PostClient.swift, Togather/Togather/MoyaClient/UserClient.swift
=> 🔀 :: (#68) Client 리팩토링

Togather/Togather/ViewModels/post/PostViewModel.swift, Togather/Togather/ViewModels/user/EmailDuplicateViewModel.swift, Togather/Togather/ViewModels/user/EmailVerifyViewModel.swift, Togather/Togather/ViewModels/user/LoginViewModel.swift, Togather/Togather/ViewModels/user/SendEmailViewModel.swift, Togather/Togather/ViewModels/user/SignUpViewModel.swift
=> 🔀 :: (#67) ViewModel 리팩토링

Togather/Togather/View/WritingView.swift, Togather/Togather/ViewModels/post/isSuccess.swift
글쓰기 기능을 추가했으나, Tag 선택 기능은 아직 구현하지 못했습니다.
close #77
=> 🔀 :: (#77) 글쓰기 기능 추가

Togather/Togather/MoyaClient/PostClient.swift, Togather/Togather/View/PostDetail.swift, Togather/Togather/View/SearchView.swift, Togather/Togather/View/myview ->/MyPost.swift
=> 🔀 :: (#79) 게시물 목록 get 버그 수정

Togather/Togather/View/HomeView.swift, Togather/Togather/View/ShowView.swift, Togather/Togather/View/TabBarView.swift
=> 🔀 :: (#81) 게시물 불러오기 기능 구현

Togather/Togather/Model/post/UserPostModel.swift
codable이 아닌 일반 스트럭트로 한 파일 더 만듬.
close #83
=> 🔀 :: (#83) post struct 추가

Togather/Togather/ViewModels/post/HomeViewModel.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift
=> 🔀 :: (#85) PostDetailViewModel

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/HomeView.swift, Togather/Togather/View/PostDetail.swift, Togather/Togather/View/SearchView.swift, Togather/Togather/View/myview ->/MyPost.swift
=> 🔀 :: (#87) PostDetailView 기능 구현

Togather/Togather/Model/post/PostDetailModel.swift
=> 🔀 :: (#89) Posts_Detail struct 추가

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> 🔀 :: (#91) Kingfisher 라이브러리 추가

Togather/Togather/DrawApp.swift, Togather/Togather/Model/post/MyPostModel.swift, Togather/Togather/Model/post/PostDetailModel.swift, Togather/Togather/Model/post/UserPostModel.swift
=> 🔀 :: (#93) model 수정

Togather/Togather/ViewModels/post/HomeViewModel.swift, Togather/Togather/ViewModels/post/MyPostViewModel.swift, Togather/Togather/ViewModels/post/PostViewModel.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift
=> 🔀 :: (#95 viewmodel 수정

Togather/Togather/View/HomeView.swift, Togather/Togather/View/PostDetail.swift, Togather/Togather/View/SearchView.swift, Togather/Togather/View/WritingView.swift, Togather/Togather/View/myview ->/MyPost.swift
=> 🔀 :: (#97) edit view

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> 🔀 :: (#102) swiftui-pull-to-refresh 라이브러리 추가

Togather/Togather/MoyaClient/PostClient.swift
=> 🔀 :: (#104) post 클라이언트 수정

Togather/Togather/View/HomeView.swift, Togather/Togather/ViewModels/post/HomeViewModel.swift
=> 🔀 :: (#107) 홈 화면 기능 수정

Togather/Togather/View/HomeView_List_Content.swift, Togather/Togather/View/myview ->/MyPost.swift, Togather/Togather/ViewModels/post/MyViewModel, Togather/Togather/ViewModels/post/MyViewModel.swift
=> 🔀 :: (#106) 내 게시물 기능 추가

Togather/Togather/Model/post/UserPostModel.swift, Togather/Togather/View/PostDetail.swift, Togather/Togather/View/WritingView.swift
=> 🔀 :: (#110) edit code

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/MoyaClient/UserClient.swift, Togather/Togather/View/SignUpView/SignUpEmailVerifyView.swift, Togather/Togather/View/SignUpView/SignUpView.swift, Togather/Togather/View/SignUpView/signUpSuccessView.swift, Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift, Togather/Togather/ViewModels/user/Change/ChangePasswordViewModel.swift, Togather/Togather/ViewModels/user/Email/EmailDuplicateViewModel.swift, Togather/Togather/ViewModels/user/Email/EmailVerifyViewModel.swift, Togather/Togather/ViewModels/user/Email/SendEmailViewModel.swift, Togather/Togather/ViewModels/user/FindPasswordEmailViewModel.swift, Togather/Togather/ViewModels/user/Get/GetMyProfileViewModel.swift, Togather/Togather/ViewModels/user/Get/GetUserProfileViewModel.swift, Togather/Togather/ViewModels/user/LogOutViewModel.swift, Togather/Togather/ViewModels/user/QuitAccountViewModel.swift, Togather/Togather/ViewModels/user/SignUp/SignUpValueCheckViewModel.swift, Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift, Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
=> 🔀 :: (#99) 회원가입 기능 추가

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Model/post/PostDetailModel.swift, Togather/Togather/Model/post/UserPostModel.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift
=> 🔀 :: (#116) is_mine 기능 추가

Togather/Togather/View/EditPostView.swift, Togather/Togather/ViewModels/post/EditPostViewModel.swift
=> 🔀 :: (#118) EditPostView 기능 추가

Togather/Togather/View/PostDetail.swift
=> 🔀 :: (#120) Navigation 추가

Togather/Togather/MoyaClient/UserClient.swift, Togather/Togather/Plugin/MoyaLoggerPlugin.swift, Togather/Togather/ViewModels/post/HomeViewModel.swift, Togather/Togather/ViewModels/post/MyViewModel.swift, Togather/Togather/ViewModels/post/PostViewModel.swift, Togather/Togather/ViewModels/post/SearchViewModel.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift, Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift, Togather/Togather/ViewModels/user/Change/ChangePasswordViewModel.swift, Togather/Togather/ViewModels/user/Email/EmailDuplicateViewModel.swift, Togather/Togather/ViewModels/user/Email/EmailVerifyViewModel.swift, Togather/Togather/ViewModels/user/Email/SendEmailViewModel.swift, Togather/Togather/ViewModels/user/FindPasswordEmailViewModel.swift, Togather/Togather/ViewModels/user/Get/GetMyProfileViewModel.swift, Togather/Togather/ViewModels/user/Get/GetUserProfileViewModel.swift, Togather/Togather/ViewModels/user/LogOutViewModel.swift, Togather/Togather/ViewModels/user/LoginViewModel.swift, Togather/Togather/ViewModels/user/QuitAccountViewModel.swift, Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift, Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
=> 🔀 :: (#124) Moya 디버깅로그 플러그인 추가

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Model/Github_Profile_Image.swift, Togather/Togather/View/myview ->/Developers.swift
=> 🔀 :: (#135) 개발자들 뷰 추가

Togather/Togather/View/HomeView.swift
=> 🔀 :: (#137) HomeView 애니메이션 추가

Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/ViewModels/user/Get/GetMyProfileViewModel.swift, Togather/Togather/ViewModels/user/Get/GetUserProfileViewModel.swift, Togather/Togather/ViewModels/user/LogOutViewModel.swift, Togather/Togather/ViewModels/user/LoginViewModel.swift, Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
=> 🔀 :: (#142) 에러 로그 리팩토링

Togather/Togather/ViewModels/post/DeletePostViewModel.swift, Togather/Togather/ViewModels/post/EditPostViewModel.swift, Togather/Togather/ViewModels/post/LikePostViewModel.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift, Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
=> 🔀 :: (#144) add plugin

Togather/Togather/View/SearchView.swift, Togather/Togather/View/SignInView.swift, Togather/Togather/View/myview ->/EditInfo.swift
=> 🔀 :: (#146) add textfield methods

Togather/Togather/Model/post/PostDetailModel.swift, Togather/Togather/MoyaClient/PostClient.swift, Togather/Togather/View/PostDetailVIew.swift
=> 🔀 :: (#148) edit like func

Togather/Togather/View/MyView.swift, Togather/Togather/View/SignUpView/SignUpView.swift, Togather/Togather/ViewModels/user/Get/GetMyProfileViewModel.swift
내 프로필 보기 기능 추가
MyView위 이미지와 이름, 이메일이 뜸
close #130
=> 🔀 :: (#130) 내 프로필 보기 추가

Togather/Togather/View/WritingView.swift
=> 🔀 :: (#154) link_keyboard 영어만 달 수 있게할거임

Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> 🔀 :: (#155) package

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> 🔀 :: (#153) package 재설치

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/View/HomeView.swift, Togather/Togather/View/MyView.swift, Togather/Togather/View/TabBarView.swift, Togather/Togather/ViewModels/user/LogOutViewModel.swift
=> 🔀 :: (#163) 로그아웃 기능 추가

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/EditPostView.swift, Togather/Togather/View/HomeView.swift, Togather/Togather/View/PostDetailVIew.swift, Togather/Togather/View/SearchTagListView.swift, Togather/Togather/View/SearchView.swift, Togather/Togather/View/TagListView.swift, Togather/Togather/View/WritingView.swift, Togather/Togather/ViewModels/post/HomeViewModel.swift, Togather/Togather/ViewModels/post/PostViewModel.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift
수정, 태그기능의 태그기능을 태그 전체보기를 사용하여 추가하도록 만들었다.
close #171
=> 🔀 :: (#171) 검색 & 수정 태그기능 업데이트

Togather/Togather/ViewModels/post/EditPostViewModel.swift, Togather/Togather/ViewModels/post/HomeViewModel.swift, Togather/Togather/ViewModels/post/MyViewModel.swift, Togather/Togather/ViewModels/post/PostViewModel.swift, Togather/Togather/ViewModels/post/SearchViewModel.swift, Togather/Togather/ViewModels/post/TagViewModel.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift, Togather/Togather/ViewModels/user/Change/ChangePasswordToEmailViewModel.swift, Togather/Togather/ViewModels/user/Email/EmailVerifyViewModel.swift, Togather/Togather/ViewModels/user/Login/LoginViewModel.swift, Togather/Togather/ViewModels/user/Profile/GetMyProfileViewModel.swift, Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift, Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
ViewModel의 통신 부분에 비동기 처리함
close #173
=> 🔀 :: (#173) ViewModel 비동기 처리

Togather/Togather/View/C언어 ㅋ.c, Togather/Togather/View/C언어 ㅋ.h, Togather/Togather/View/PostDetailVIew.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift
=> 🔀 :: (#177) 좋아요 기능 버그 수정

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/C언어 ㅋ.c, Togather/Togather/View/HomeView.swift, Togather/Togather/View/SearchTagListView.swift, Togather/Togather/View/SearchView.swift
=> 🔀 :: (#178) 태그 검색 수정

Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/ContentView.swift, Togather/Togather/DrawApp.swift, Togather/Togather/View/MyView.swift, Togather/Togather/View/ShowView.swift, Togather/Togather/View/SignInView.swift, Togather/Togather/View/SignUpView/SignUpEmailVerifyView.swift, Togather/Togather/View/SignUpView/SignUpView.swift, Togather/Togather/View/SignUpView/signUpSuccessView.swift, Togather/Togather/View/TabBarView.swift, Togather/Togather/View/WritingView.swift, Togather/Togather/View/myview ->/EditInfo.swift, Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordSuccessView.swift, Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordVerifyView.swift, Togather/Togather/View/myview ->/PasswordChangeView/EnterNewPasswordView.swift
=> 🔀 :: (#181) @available(iOS 16.0, *) 추가

Togather/Togather/ContentView.swift, Togather/Togather/View/HomeView.swift, Togather/Togather/View/MyView.swift, Togather/Togather/View/PostDetailVIew.swift, Togather/Togather/View/SearchView.swift, Togather/Togather/View/SignInView.swift, Togather/Togather/View/myview ->/DeleteAccount.swift, Togather/Togather/View/myview ->/Developers.swift, Togather/Togather/View/myview ->/EditInfo.swift, Togather/Togather/View/myview ->/MyPost.swift, Togather/Togather/ViewModels/user/Email/EmailVerifyViewModel.swift
=> 🔀 :: (#187) BackgroundColor 변수 이름 변경

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Extension/PositionChangeExtension.swift, Togather/Togather/Model/user/UserProfileUDModel.swift, Togather/Togather/View/MyView.swift, Togather/Togather/View/myview ->/EditInfoView.swift, Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift, Togather/Togather/ViewModels/user/Login/LoginViewModel.swift, Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift
프로필 포지션 태그 UI 추가하고, 변환하는 Extension 추가함
close #194
=> 🔀 :: (#194) 프로필 포지션 태그 UI

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordEmailView.swift
비밀번호 변경 이메일 인증 뷰 만들었다.
close #196
=> 🔀 :: (#196) 비밀번호 변경 이메일 인증 뷰

Togather/Togather/Assets.xcassets/Color/main-Elevated.colorset/Contents.json, Togather/Togather/Assets.xcassets/Color/main.colorset/Contents.json, Togather/Togather/Assets.xcassets/Color/red.colorset/Contents.json, Togather/Togather/Assets.xcassets/Color/white-Elevated1.colorset/Contents.json, Togather/Togather/Assets.xcassets/Color/white-Elevated2.colorset/Contents.json, Togather/Togather/Assets.xcassets/Color/white-Elevated3.colorset/Contents.json, Togather/Togather/Assets.xcassets/Color/white-Elevated4.colorset/Contents.json, Togather/Togather/Assets.xcassets/Color/white.colorset/Contents.json
=> 🔀 :: (#198) 색상추가

Togather/Togather/Assets.xcassets/Color/text0.colorset/Contents.json
=> 🔀 :: (#200) 디자인 시스템 색상

Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordEmailView.swift
=> 🔀 :: (#203) 비밀번호 변경 VM 연결

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/ContentView.swift, Togather/Togather/View/LoginView.swift, Togather/Togather/View/MyView.swift, Togather/Togather/View/myview ->/EditInfoView.swift, Togather/Togather/ViewModels/user/Login/LoginViewModel.swift
=> 🔀 :: (#205) 로그인 오류처리

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/Resources/Assets.xcassets/Color/text1.colorset/Contents.json, Togather/Togather/Soket/SocketTest.swift, Togather/Togather/View/chat/ChatListView.swift, Togather/Togather/View/chat/ChattingView.swift, Togather/Togather/View/chat/DividingLine.swift, Togather/Togather/View/chat/MyChat.swift, Togather/Togather/View/chat/OpponentChat.swift, Togather/Togather/View/component/BackBtn.swift, Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordEmailView.swift
=> 🔀 :: (#215) 채팅 UI

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/Model/post/PostDetailModel.swift, Togather/Togather/Resources/Font/Font.swift, Togather/Togather/Sources/Components/PostDetail/PostInfoForm.swift, Togather/Togather/Sources/Scene/Login/LoginButton/LoginNavigationButton.swift, Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift, Togather/Togather/View/chat/ChattingView.swift, Togather/Togather/ViewModels/post/postDetailViewModel.swift
=> 🔀 :: (#229) 세부 게시물 뷰 리팩토링

Togather/Togather/Sources/Scene/Search/View/SearchView.swift, Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift
스크롤 범위 이상한거, 게시글 잘 안보이는거 수정했습니다
close #240
=> 🔀 :: (#240) 검색 뷰 버그 수정

Togather/Togather/Network/MoyaClient/ImageClient.swift, Togather/Togather/View/myview ->/EditInfoView.swift, Togather/Togather/View/myview ->/ImagePicker.swift, Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
=> 🔀 :: (#238) 프로필 이미지 변경

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/Sources/Scene/Home/View/HomeView.swift, Togather/Togather/View/TabBarView.swift
=> 🔀 :: (#243) undo tabbarview

Togather/Togather/Sources/Components/Home/PostForm.swift, Togather/Togather/Sources/Scene/Home/View/HomeView.swift, Togather/Togather/Sources/Scene/Login/View/LoginView.swift, Togather/Togather/Sources/Scene/MyView/View/MyView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/MyPostView.swift, Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift, Togather/Togather/Sources/Scene/Search/View/SearchView.swift, Togather/Togather/Sources/Scene/TabBar/View/TabBarView.swift, Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift, Togather/Togather/View/ChangePasswordSuccessView.swift
=> 🔀 :: (#249) private 추가

Togather/Togather/Sources/Scene/MyView/View/myview ->/DevelopersView.swift
=> 🔀 :: (#251) 개발자 인원 추가

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Sources/Components/Auth/AuthTextField.swift, Togather/Togather/Sources/Components/Post/PostButton.swift, Togather/Togather/Sources/Components/Post/PostTextEditor.swift, Togather/Togather/Sources/Components/Post/PostTextField.swift, Togather/Togather/Sources/Components/PostDetail/PostInfoForm.swift, Togather/Togather/Sources/Components/Search/SearchTagLabel.swift, Togather/Togather/Sources/Components/Search/SearchTextField.swift, Togather/Togather/Sources/Scene/Home/Model/UserPostModel.swift, Togather/Togather/Sources/Scene/PostDetail/Model/PostDetailModel.swift, Togather/Togather/View/chat/ChatListView.swift, Togather/Togather/View/chat/ChattingView.swift, Togather/Togather/View/chat/MyChat.swift, Togather/Togather/View/chat/OpponentChat.swift
=> 🔀 :: (#253) change var to let

Togather/Togather.xcodeproj/xcshareddata/xcschemes/Togather.xcscheme, Togather/Togather/Model/UploadImageModel.swift, Togather/Togather/Model/user/UserProfileUDModel.swift, Togather/Togather/Network/MoyaClient/ImageClient.swift, Togather/Togather/Sources/Components/Home/PostForm.swift, Togather/Togather/Sources/Scene/MyView/View/MyView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/ImagePicker.swift, Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift, Togather/Togather/View/chat/ChatListView.swift, Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
=> 🔀 :: (#256) change profile image

Togather/Togather/Model/chat/ChatListModel.swift, Togather/Togather/Network/MoyaClient/ChatClient.swift, Togather/Togather/View/chat/ChatListView.swift, Togather/Togather/ViewModels/chat/ChattingListViewModel.swift
=> 🔀 :: (#258) 채팅 리스트 서버 연동

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Sources/Scene/MyView/View/MyView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift, Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
=> 🔀 :: (#260) 프로필 이미지 변경 버그

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/Network/MoyaClient/ImageClient.swift, Togather/Togather/Network/MoyaClient/PostClient.swift, Togather/Togather/Network/MoyaClient/SocketClient.swift, Togather/Togather/Network/MoyaClient/UserClient.swift, Togather/Togather/Sources/Components/Auth/AuthButton.swift, Togather/Togather/Sources/Components/MyView/ChagePassword/ChangePasswordButton.swift, Togather/Togather/Sources/Components/MyView/ChagePassword/ChangePasswordTextField.swift, Togather/Togather/Sources/Components/MyView/ChagePassword/ChangePasswordTitle.swift, Togather/Togather/Sources/Components/MyView/DeleteAccount/DeleteAcountButton.swift, Togather/Togather/Sources/Components/MyView/EditInfo/EditInfoTextEditor.swift, Togather/Togather/Sources/Components/MyView/EditInfo/EditInfoTextField.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift, Togather/Togather/Sources/Scene/MyView/ViewModel/EditInfo/ChangeMyInfoViewModel.swift, Togather/Togather/Sources/Scene/MyView/ViewModel/Logout/LogoutViewModel.swift, Togather/Togather/Sources/Scene/MyView/ViewModel/QuitAccount/QuitAccountViewModel.swift, Togather/Togather/View/ChangePasswordEmailView.swift, Togather/Togather/View/ChangePasswordVerifyView.swift, Togather/Togather/View/EnterNewPasswordView.swift, Togather/Togather/ViewModels/user/ChangePasswordToEmailViewModel.swift, Togather/Togather/ViewModels/user/TokenAuthViewModel.swift, Togather/Togather/ViewModels/user/UserProfileViewModel.swift
=> 🔀 :: (#263) 계정 삭제 뷰 리팩토링

Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
리팩토링 한 내용 리팩토링
사진 변경 시 UserDefault 에 저장되어 이상하게 작동되는 오류 수정
=> 🔀 :: (#267) image refactoring

CODEOWNERS
=> CODEOWNER team -> individual

CODEOWNERS
=> codeowner 수정

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/.swiftlint.yml
- Lint 를 추가합니다
- Lint 를 추가합니다
- Lint 를 추가합니다
X
=> 🔧 :: (#279) swift lint

Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/Model/user/UserProfileUDModel.swift, Togather/Togather/Network/Header/Header.swift
swiftKeychain 라이브러리 추가
close #296
=> 🔀 :: swiftkeychain library

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Togather/Togather/Sources/Application/ContentView.swift, Togather/Togather/Sources/Application/ContentViewModel.swift, Togather/Togather/Sources/Scene/Login/ViewModel/LoginViewModel.swift, Togather/Togather/Sources/Scene/MyView/ViewModel/Logout/LogoutViewModel.swift
=> 🔀 :: auto login

Togather/Togather/.swiftlint.yml
lint 함수 최대 길이 제외시켰습니다
close #300
=> 🔀 ::  lint 함수 최대 길이 제외

Togather/Togather/Sources/Scene/MyView/ViewModel/QuitAccount/QuitAccountViewModel.swift
=> 🔀 :: (#306) QuitAccountViewModel

Togather/Togather/Sources/Components/MyView/DeleteAccount/DeleteAcountButton.swift, Togather/Togather/Sources/Components/MyView/EditInfo/EditInfoTextEditor.swift, Togather/Togather/Sources/Components/Post/PostButton.swift, Togather/Togather/Sources/Scene/LoginChangePassword/VIew/ChangePasswordEmailSuccessView.swift
=> 🔀 :: (#311) delete 주석

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Sources/Components/Chat/DividingLine.swift, Togather/Togather/Sources/Components/Chat/MyChat.swift, Togather/Togather/Sources/Components/Chat/OpponentChat.swift, Togather/Togather/Sources/Components/PostDetail/PostInfoForm.swift, Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift, Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift, Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
채팅 입력창 디자인 수정 및 읽음 기능 추가
close #314
=> 🔀 :: (#314) 채팅 디자인 대응 및 기능 추가

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Network/MoyaClient/ChatClient.swift, Togather/Togather/Soket/View/SocketTest.swift, Togather/Togather/Sources/Components/Chat/OpponentChat.swift, Togather/Togather/Sources/Scene/Chat/Model/ChattingDataModel.swift, Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift, Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift, Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift, Togather/Togather/Sources/Scene/Chat/ViewModel/SocketViewModel.swift
병진님 린트 설치하세요.병진님 린트 설치하세요.병진님 린트 설치하세요.병진님 린트 설치하세요.병진님 린트 설치하세요.병진님 린트 설치하세요.
=> 🔀 :: (#318) lint 수정

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift, Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift, Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift
=> 🔀 :: (#316) 게시물 수정 버그 수정

Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift, Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift, Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift, Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
=> 🔀 :: (#322) 실시간 채팅 구현

Togather/Togather/Sources/Components/Home/PostForm.swift, Togather/Togather/Sources/Scene/Home/View/HomeView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/MyPostView.swift, Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift, Togather/Togather/Sources/Scene/PostDetail/ViewModel/PostDetailViewModel.swift, Togather/Togather/Sources/Scene/Search/View/SearchView.swift, Togather/Togather/Sources/Scene/TabBar/View/ShowView.swift
=> 🔀 :: (#324) 연락 하기 기능

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Network/MoyaClient/ChatClient.swift, Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift, Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
=> 🔀 :: (#325) 채팅 기능 추가 및 수정

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Sources/Components/Chat/ChattingSkeleton.swift, Togather/Togather/Sources/Components/Chat/MychatSkeleton.swift, Togather/Togather/Sources/Components/Chat/OpponentChatSkeleton.swift, Togather/Togather/Sources/Extension/Date+timeFormat.swift, Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift, Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
=> 🔀 :: (#331) 채팅 스켈레톤 완성

Togather/Togather.xcodeproj/project.pbxproj, Togather/Togather/Sources/Components/BackgroundTapGesture/BackgroundTapGesture.swift, Togather/Togather/Sources/Extension/UIApplication+endEditing.swift, Togather/Togather/Sources/Scene/ChangePassword/View/ChangePasswordVerifyView.swift, Togather/Togather/Sources/Scene/ChangePassword/View/EnterNewPasswordView.swift, Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift, Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift, Togather/Togather/Sources/Scene/Login/View/LoginView.swift, Togather/Togather/Sources/Scene/LoginChangePassword/VIew/ChangeLostPasswordView.swift, Togather/Togather/Sources/Scene/LoginChangePassword/VIew/ChangePasswordEmailView.swift, Togather/Togather/Sources/Scene/LoginChangePassword/VIew/EmailVerifyView.swift, Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift, Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift, Togather/Togather/Sources/Scene/Search/View/SearchView.swift, Togather/Togather/Sources/Scene/SignUp/View/SignUpEmailVerifyView.swift, Togather/Togather/Sources/Scene/SignUp/View/SignUpView.swift, Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift, Togather/Togather/SupportingFiles/Info.plist
=> 🔀 :: (#333) 키보드 클릭시 dissmis
